### PR TITLE
Completed query 9

### PR DESCRIPTION
**Pull request by Michi18**

### CODE REVIEW

**Review by pmyrsi — CHANGES_REQUESTED** [review]
This solution shows the second-to-last review, but not the last review. The tasks intention was to show in **one** row both the last review and the second-to-last review (for example column `LAST_REVIEW_SCORE_ACCURACY` and `PREVIOUS_REVIEW_SCORE_ACCURACY`) side by side.

**Review by pmyrsi — CHANGES_REQUESTED** [review]
Alright, this works but is not optimal - you're querying the `Revs` CTE twice in `R_one` and `R_two`. Could you please change it so that there's only one CTE that gets both the last row and the second to last from `Revs`, putting them both to different columns? 🤔

**Review by pmyrsi — APPROVED** [review]
Generally speaking good job, the `WHERE rn =1 or rn = 2` filtration is not 100% necessary (but I guess buys a bit of querying speed ;) )

**Comment by Michi18** [comment]
Yes, it buys a bit of querying speed and it's more readable to me

**Pull request merged**
